//
// Created by jiezhuchen on 22-4-19.
//

#ifndef LEARNOPENGL_GLWHITEBOARDJNIBRIDGE_H
#define LEARNOPENGL_GLWHITEBOARDJNIBRIDGE_H


class GLWhiteBoardJNIBridge {

};


#endif //LEARNOPENGL_GLWHITEBOARDJNIBRIDGE_H
